---
name: bump

on: [repository_dispatch]


jobs:
  bump:
    if: github.event_name == 'repository_dispatch' && github.event.action == 'tag'
    runs-on: ubuntu-latest
    steps:
    - name: Information
      run: |
        echo "'${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PYFRC_ACCESS_TOKEN }}
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        pip install gitpython

    - name: Bump Requirements
      run: |
        python update_req.py '${{ github.event.client_payload.repository }}' '${{ github.event.client_payload.package_name }}'

    - name: Push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Github Action"
        git add requirements.txt
        git commit -m "Bump '${{ github.event.client_payload.package_name }}' dependency"
        git push

    - name: Get Previous tag
      id: previoustag
      uses: WyriHaximus/github-action-get-previous-tag@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get next tag version
      id: semvers
      uses: WyriHaximus/github-action-next-semvers@master
      with:
        version: ${{ steps.previoustag.outputs.tag }}

    - name: Push New Tag
      run: |
        git tag ${{ steps.semvers.outputs.patch }}
        git push --tags

        

    # - name: Push changes
    #   uses: ad-m/github-push-action@master
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}

    # - name: Bump Version and push Tag
    #   uses: mathieudutour/github-tag-action@v3
    #   env:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     create_annotated_tag: true
    #     default_bump: patch
    #     tag_prefix: ""
    # - name: Ping ourselves to push
    #   run: |
    #     curl -X POST https://api.github.com/repos/TheTripleV/pyfrc/dispatches \
    #         -H 'Accept: application/vnd.github.everest-preview+json' \
    #         -u TheTripleV:${{ secrets.PYFRC_ACCESS_TOKEN }} \
    #         --data '{"event_type": "pub", "client_payload": { "msg": "publish action"}}'
